dist: xenial
addons:
  apt:
    packages:
      - rabbitmq-server
services:
  - rabbitmq

language: python
python:
  - "3.6"

branches:
  only:
  - master
  - develop
  - /^release-.*$/
  - travis-test

install:
  - go get github.com/icon-project/rewardcalculator/cmd/icon_rc
  - pip install -r requirements.txt

script:
  - python setup.py test

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: iconfoundation
  password: $PYPI_PW
  on:
    branch: master
